# Generated by Django 5.2.3 on 2026-04-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0007_user_area_serves_user_whatsapp_number_poll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
