# Generated by Django 5.2.3 on 2026-05-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='contact_info',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='pricing',
            field=models.BigIntegerField(),
        ),
    ]
