# Generated by Django 6.0.4 on 2026-04-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0007_user_area_serves_user_whatsapp_number_poll_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verification_images/')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='prop.franchiseproperty')),
            ],
        ),
    ]
