# Generated by Django 6.0.4 on 2026-04-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0008_franchisepropertyimage'),
        ('prop', '0008_newskeyword'),
    ]

    operations = [
    ]
